### ISSUE TITLE
Bridge to another ecosystem

### ISSUE THREAD

**Issue by Billcrypto6** [sora-xor/rfps#15]
As a cryptocurrency lover, Sora is a very innovative project and I would like to make a proposal that many users in Polkaswap with the incoming and outgoing bridge with the eth network are the high cost of fees and an alternative bridge can be made either : Solana, Binance Chain, Cosmos, moonbeam and it can be done as soon as possible.

**Comment by WRRicht3r** [comment]
Hello, could you please follow the guidelines in https://github.com/sora-xor/rfps/blob/master/README.md and create a pull request to merge here https://github.com/sora-xor/rfps/tree/master/open_rfps
Thank you!

**Comment by newwayventures** [comment]
I have created  #17. The first is between BSC and SORA networks.
