### ISSUE TITLE
[RFP]: Granting of research, reports and education for SORA News

### ISSUE THREAD

**Issue by Grugonion** [sora-xor/rfps#61]
### Proposal Due Date

07/28/2023

### Proposal Overview

We are excited to present our grant proposal on behalf of SORA News, a trusted news and blog website, seeking to enhance our contributions to the SORA ecosystem. With more than 2700 hours invested in providing informative content, our proposal outlines a comprehensive plan to expand our impact on community engagement and contribute to the growth and success of the SORA. Over the course of its establishment, SORA News has demonstrated an impressive track record, effectively solidifying its position as a reputable source of information within the SORA ecosystem. Here are some key points highlighting the past performance and achievements of the SORA News:

**Strong Social Media Presence:** 
SORA News successfully cultivated a dedicated following on Twitter, amassing an impressive 4.4k Twitter followers. This substantial audience reflects the website's ability to engage users and deliver content that resonates with the community.

**Extensive News and Blog Posts:** 
The website has proven its commitment to providing comprehensive coverage of the SORA ecosystem. With more than 17 news and blog posts dedicated to SORA-related topics, SORA News has consistently delivered timely and relevant content to its readership.

**Consistent Traffic Growth:** 
Within just three months of the inception of the website, SORA News attracted 2k unique page visitors. This inflow of traffic indicates the website's capacity to draw in an increasing number of readers.

**Social Media Reach:** 
Over the same three-month period, SORA News achieved a remarkable 109k Twitter impressions. This metric signifies our ability to effectively disseminate information across social media platforms, expanding its influence and reach over the SORA community.

**Positive Community Feedback:** 
The dedication and quality of the content provided by SORA News have been met with great feedback from the SORA community. This positive response attests to the website's credibility and reliability as a source of news and information.

### Proposal Goals

The primary goal of this proposal is to secure the necessary resources and support for SORA News to significantly enhance its contributions to the SORA ecosystem.

This proposal outlines strategic initiatives and resource allocations to achieve the following objectives:

**Delivering High-Quality Content:** 
The proposal aims to ensure the consistent delivery of high-quality news articles, blog posts, and educational materials related to the SORA project. By providing well-researched and insightful content, SORA News will keep the community well-informed and educated about SORA's developments and advancements.

**Fostering Community Engagement:** 
To enhance direct communication and foster community engagement, the proposal advocates for the implementation of email marketing campaigns for monthly news updates. These initiatives aim to establish personal connections with community members and encourage active participation.

**Promoting Inclusivity:** 
The proposal recognizes the need to reach a broader audience within the SORA community. To achieve this, the grant will be utilized to create a Spanish version of the website, catering to Spanish-speaking individuals.

**Bridging the Educational Gap:** 
SORA News is committed to addressing the educational gap within the SORA ecosystem. By allocating funds for additional educational materials, the proposal seeks to empower community members with a deeper understanding of the SORA project, blockchain technology, and decentralized finance concepts.

**Ensuring Content Quality and Consistency:** 
To overcome the challenges of maintaining content quality and consistency, the proposal advocates for the hiring of a dedicated full-time team member. This strategic addition will ensure that SORA News can deliver timely and accurate updates, improving the overall impact of the platform.

**Building Credibility and Trust:** 
By securing funding and consistently delivering reliable content, SORA News aims to build credibility and trust within the SORA ecosystem. This proposal seeks to reinforce SORA News as a reliable and respected source of information, addressing concerns related to misinformation and fostering greater confidence among community members.

### Scope of Work

Our proposal outlines a comprehensive scope of work that encompasses several key areas:

**Content Creation:** 
The grant will support the creation of **high-quality news articles, blog posts, and educational materials**, ensuring consistent and valuable information reaches the SORA community.

**Website Maintenance and Hosting:** 
A portion of the grant will be allocated to maintaining our website, optimizing user experience, and ensuring seamless accessibility for community members.

**Full-Time Team Member:** 
We seek funding to hire a dedicated full-time individual to improve content quality, enhance engagement, and address the evolving needs of the SORA ecosystem.

**Spanish Website Version:** 
To promote inclusivity, the grant will support the establishment of a Spanish version of our website, catering to Spanish-speaking SROA members.

**Email Marketing and Community Engagement:** 
Funds will be used to implement an email subscription feature and consistent email marketing to foster direct communication with the SORA community.

### Current Roadblocks and Barriers to Success

We recognize that there are some significant roadblocks and barriers hindering our ability to achieve the level of success and impact we envision within the SORA ecosystem.

**Insufficient Human Resources:**
At present, our team faces a shortage of dedicated human resources, particularly the absence of a full-time individual dedicated to SORA News. To ensure that we consistently deliver high-quality work and timely updates to the community, having at least one individual working full-time on SORA News is necessary. This limits our capacity to expand and deliver content in a timely manner, hindering our ability to effectively serve the needs of the SORA ecosystem.

**Financial Constraints:**
One of the primary roadblocks we currently face is the lack of sufficient funds to maintain the website and sustain the continuous flow of high-quality content. Operating a news and blog requires resources to cover hosting fees, domain renewals, content creation, and compensation. As our primary focus lies in delivering informative and insightful content to the SORA community, inadequate funding hampers our ability to scale our operations and maintain a consistent level of service.

### Evaluation Metrics and Criteria

To measure the impact and success of SORA News' contributions to the SORA ecosystem, we have identified specific evaluation metrics and criteria. These metrics focus on community engagement, content quality, and educational initiatives, all of which are essential for achieving our proposal's goals.

**1. Twitter Likes and Retweets:**
One of the key metrics for evaluating our impact on social media is the number of Twitter likes and retweets. By tracking engagement on our Twitter posts, we can gauge the level of interest and interaction from the SORA community. An increase in likes and retweets signifies that our content resonates with the audience and successfully disseminates valuable information.

**2. News Coverage of the SORA Ecosystem:**
Another crucial metric is the comprehensive coverage of impactful news related to the SORA ecosystem. We will monitor our ability to deliver timely updates on significant developments, events, and milestones within the SORA project. By providing reliable and well-researched news articles and blog posts, we aim to keep the community well-informed and engaged.

**3. Educational Category on SORA News Website:**
The establishment of an educational category on the SORA News website is an essential aspect of our proposal. To assess the success of this initiative, we will measure the number of educational materials produced, their depth and relevance, and the level of engagement they receive from the community. We aim to make a knowledgeable community through accessible and informative educational content.

**4. Community Feedback and Engagement:**
Feedback from the SORA community is a valuable indicator of our performance. We will actively monitor and evaluate community responses to our content, seeking insights into its usefulness and impact. Positive feedback, active discussions, and constructive interactions demonstrate our ability to meet the needs and interests of the community effectively.

**5. Website Traffic and Engagement:**
Monitoring website traffic and engagement metrics, such as the number of unique visitors, time spent on the website, and page views, will help us understand the reach and influence of SORA News. Increased traffic indicates the success of our efforts to provide valuable content and attract a broader audience to the SORA ecosystem.

**6. Inclusivity and Reach:**
The success of our efforts to promote inclusivity within the SORA ecosystem will be evaluated through the launch and performance of the Spanish version of the website. Increased engagement and interactions with Spanish-speaking users will be an important indicator of the effectiveness of this initiative.

**7. Content Accuracy and Credibility:**
Maintaining content accuracy and credibility is vital to our reputation as a reliable news and educational platform. Regularly assessing the accuracy of our information and maintaining a commitment to fact-checking ensures that we remain a trustworthy source of information within the SORA community.

### Submission Requirements

To ensure that the SORA News proposal for the SORA ecosystem is reviewed and considered a success, the submission should fulfill the following criteria:

**1. Alignment with SORA Ecosystem Vision:** 
The proposal should clearly demonstrate how SORA News' initiatives align with the vision, goals, and mission of the SORA ecosystem. It should emphasize how the contributions of SORA News will support the growth, adoption, and success of the SORA project.

**2. Impactful and Valuable Contributions:** 
The submission should showcase how SORA News' involvement will bring value to the SORA community. Emphasis should be placed on providing informative and engaging content, fostering community engagement, and promoting education about the SORA ecosystem.

**3. Measurable Objectives and Key Performance Indicators (KPIs):** 
The proposal should outline specific and measurable objectives that can be tracked through key performance indicators (KPIs). These metrics should enable the evaluation of the success and effectiveness of SORA News' initiatives within the SORA ecosystem.

**5. Content Quality and Credibility:** 
SORA News' commitment to providing accurate and reliable information is essential. The proposal should highlight measures to maintain content quality, fact-checking procedures, and sourcing credible information to ensure the platform's integrity.

**6. Engagement and Inclusivity:** 
The submission should emphasize efforts to actively engage with the SORA community and promote inclusivity. Initiatives that encourage community feedback, foster discussions, and cater to diverse audiences will be highly valued.

**7. Educational Impact:** 
SORA News' educational category should be well-defined, showcasing how it will bridge the educational gap within the SORA ecosystem. The proposal should describe the type of educational materials to be produced and their potential to empower the community with knowledge about SORA.

**8. Long-Term Sustainability:** 
The proposal should address the long-term sustainability of SORA News' efforts beyond the grant period. It should demonstrate how the platform plans to continue providing valuable content, engaging the community, and supporting the SORA ecosystem in the future.

**9. Expertise and Dedication:** 
SORA News should highlight the expertise and dedication of its team in delivering high-quality content and engaging with the SORA community. Demonstrating a committed and capable team will enhance the proposal's credibility.

### Submission Method

Other

### Project Due Date

01.01.2024

### Budget Amount

SORA News has invested substantial time and effort, totaling more than 2700 hours, in contributing to the SORA ecosystem. To ensure the continuation of our impactful work until the end of the year 2023, we are seeking a budget of $20,000. This funding will be crucial in addressing the following key aspects of our operations: Content creation, website maintenance, human resources, and email marketing.

**Comment by WRRicht3r** [comment]
Thank you for your submission, we will review it and get back to you

**Comment by Grugonion** [comment]
Thank you, William!

**Comment by Grugonion** [comment]
There is also the following condition brought up by me.

1. Convert $20k worth of TBCD into XOR. The exact amount of XOR we will receive will depend on the current market price of XOR at the time of the exchange.

2. After obtaining the XOR, I will set it to lock based on the following schedule:

A portion of the XOR (~17.3k) is kept liquid for immediate operational use.
Four portions of ~17.3k XOR each are set to unlock at the end of August, September, October, and November 2023 respectively. That means:
—Lock ~17.3k XOR until 31/August/2023
—Lock ~17.3k XOR until 31/September/2023
—Lock ~17.3k XOR until 31/October/2023
—Lock ~17.3k XOR until 31/November/2023

**Comment by Grugonion** [comment]
In response to the community's input, we're making key modifications to our RFP process. We'll implement a new approach based on monthly tracking and funding requests. This decision emerged from the discussions with the Sora councils and includes the following adjustments.

SORANEWS will receive initial funding of $5k for the first month and the work done until now. Following this, from the next month until January 2024, we'll be allocating $4k monthly. These funds will support our ongoing efforts, and we'll be submitting new RFPs each month to maintain transparency and accountability.

**Comment by WRRicht3r** [comment]
The first part of the grant payout was successfully implemented through governance as [Referenda 224](https://sora.subscan.io/referenda/224)
