### ISSUE TITLE
[RFP]: Granting of research, reports and education for SORA News, August

### ISSUE THREAD

**Issue by Grugonion** [sora-xor/rfps#63]
### Proposal Due Date

24/08/2023

### Proposal Overview

SORA News proudly presents its August grant RFP. We have consistently worked towards providing unbiased and in-depth news content for the SORA community, creating an informative and engaging space for all stakeholders. To continue our endeavors and amplify our impact, we are actively seeking community support to fund SORA News.
**Transparency Report:**
We invite you to view our August Transparency Report to understand our past endeavors, expenditures, and the results we have achieved: [[Transparency Report - August]](https://docs.google.com/document/d/1eOlSLTJumXuYHeFrXTXgKjOMc3aXXzI7udq6g24Z28g/edit?usp=sharing)
Overall we achieved during August 101.4k Twitter impressions and wrote 6 Articles. More can be found in the transparency report!
 

### Proposal Goals

The primary goal of this proposal is to secure the necessary resources and support for SORA News to significantly enhance its contributions to the SORA ecosystem.

This proposal outlines strategic initiatives and resource allocations to achieve the following objectives:

**Delivering High-Quality Content:**
The proposal aims to ensure the consistent delivery of high-quality news articles, blog posts, and educational materials related to the SORA project. By providing well-researched and insightful content, SORA News will keep the community well-informed and educated about SORA's developments and advancements.

**Fostering Community Engagement:**
To enhance direct communication and foster community engagement, the proposal advocates for the implementation of email marketing campaigns for monthly news updates. These initiatives aim to establish personal connections with community members and encourage active participation.

**Promoting Inclusivity:**
The proposal recognizes the need to reach a broader audience within the SORA community. To achieve this, the grant will be utilized to create a Spanish version of the website, catering to Spanish-speaking individuals.

**Bridging the Educational Gap:**
SORA News is committed to addressing the educational gap within the SORA ecosystem. By allocating funds for additional educational materials, the proposal seeks to empower community members with a deeper understanding of the SORA project, blockchain technology, and decentralized finance concepts.

**Ensuring Content Quality and Consistency:**
To overcome the challenges of maintaining content quality and consistency, the proposal advocates for the hiring of a dedicated full-time team member. This strategic addition will ensure that SORA News can deliver timely and accurate updates, improving the overall impact of the platform.

**Building Credibility and Trust:**
By securing funding and consistently delivering reliable content, SORA News aims to build credibility and trust within the SORA ecosystem. This proposal seeks to reinforce SORA News as a reliable and respected source of information, addressing concerns related to misinformation and fostering greater confidence among community members.

### Scope of Work

Our proposal outlines a comprehensive scope of work that encompasses several key areas:

Content Creation:
The grant will support the creation of high-quality news articles, blog posts, and educational materials, ensuring consistent and valuable information reaches the SORA community.

Website Maintenance and Hosting:
A portion of the grant will be allocated to maintaining our website, optimizing user experience, and ensuring seamless accessibility for community members.

Collaborating with a Polkadot Influencer
To increase the communication outreach of the product launch of Synthetic assets we have an agreement with a top Polkadot influencer who will promote SORA synthetic assets. 

Spanish Website Version:
To promote inclusivity, the grant will support the establishment of a Spanish version of our website, catering to Spanish-speaking SROA members.

Email Marketing and Community Engagement:
Funds will be used to implement an email subscription feature and consistent email marketing to foster direct communication with the SORA community.

### Current Roadblocks and Barriers to Success

This is written in the last RFP: [[here]](https://github.com/sora-xor/rfps/issues/61)

### Evaluation Metrics and Criteria

This is written in the last RFP: [[here]](https://github.com/sora-xor/rfps/issues/61) 

### Submission Requirements

This is written in the last RFP: [[here]](https://github.com/sora-xor/rfps/issues/61) 

### Submission Method

Other

### Project Due Date

30/09/2023

### Budget Amount

As agreed in the last RFP discussion, we are seeking a budget of $6k in TBCD.

**Comment by WRRicht3r** [comment]
Paid in full (more information [here](https://github.com/orgs/sora-xor/projects/24/views/1?pane=issue&itemId=37714358))
