### ISSUE TITLE
[RFP]: SORA Community Funding for Polkadot Parachain Auction

### ISSUE THREAD

**Issue by xorurai** [sora-xor/rfps#69]
### Proposal Due Date

November 2023

### Proposal Overview

• Postpone December invoice payment for devs
• Use postponed funds to buy DOT tokens
• Participate in the Polkadot Parachain auction
• If successful, devs can be paid later or in gold synthetics

### Proposal Goals

Objective: Secure a Polkadot Parachain slot for the SORA network by allocating funds from December invoice to buy DOT tokens.

### Scope of Work

not much work, just deviation of fund. 

### Current Roadblocks and Barriers to Success

• Winning a Parachain slot will boost SORA's presence in the Polkadot ecosystem
• Increased interoperability and connectivity with other projects
• Enhanced growth potential for the SORA network

### Evaluation Metrics and Criteria

• October and November: Pay devs as usual
• December: Postpone invoice payment and use funds to buy DOT tokens
• Participate in the Parachain auction
• If successful, arrange alternative payment for devs

### Submission Requirements

This plan is based because it shows the SORA community's commitment to expanding its reach and influence in the Polkadot ecosystem. By reallocating funds to secure a Parachain slot, we're investing in the future growth and success of the SORA network. Let's make it happen, bros!

### Submission Method

Blockchain: Mainnet

### Project Due Date

December 2023 - January 2024

### Budget Amount

DOT current price is  at $3.66
To have 300,000 DOT we would need $1,098,000 USD + gas fees. 

EST. $1.2M USD

**Comment by WRRicht3r** [comment]
Polkadot parachain was secured through community contributions, thanks for your proposal.
