### ISSUE TITLE
[RFP]: Ban XOR seller On-chain and from SORA main telegram

### ISSUE THREAD

**Issue by Grugonion** [sora-xor/rfps#72]
### Proposal Due Date

Today

### Proposal Overview

Rekt XOR sellers now

### Proposal Goals

Pump xor

### Scope of Work

Lfg

### Current Roadblocks and Barriers to Success

Nothing

### Evaluation Metrics and Criteria

Just ban them

### Submission Requirements

Lol

### Submission Method

Other

**Comment by WRRicht3r** [comment]
Hello, please refrain from using the RFP platform for jokes. 
Thanks.
